paths:
  /api/users/:
    get:
      summary: 'Ambil daftar pengguna'
      description: 'Mengambil daftar semua pengguna dari database'
      tags:
        - Users
      responses:
        '200':
          description: 'Berhasil mengambil daftar pengguna'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'OK'
                  message:
                    type: string
                    example: 'Users fetched successfully'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '123456'
                        name:
                          type: string
                          example: "Farid Nu'man"
                        email:
                          type: string
                          example: 'farid@example.com'
                        password:
                          type: string
                          example: 'hashedpassword123'
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
        '500':
          description: 'Kesalahan server'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'error'
                  message:
                    type: string
                    example: 'Internal server error'
